### ISSUE TITLE
Error After Instantiating Infusionsoft

### ISSUE THREAD

**Issue by SSICWeb** [justinhandley/infusionsoft-javascript-api#10]
Hello,

I receive the below error after instantiating DataContext with my Infusionsoft token.

const infusionsoft = new api.DataContext(`${infusionAccessToken}`);

This works correctly when I use the no longer maintained infusionsoft-api library.  I'm importing the library rather than using require because it is not defined in my ES module scope (this may not have any bearing on the issue). 

Do you have any ideas?  It's really odd as I'm not doing anything out of the norm and it works with the older library.  The older library is returning an error when returning a promise, but you can access the API.

Console error:

\node_modules\infusionsoft-javascript-api\lib\Queryable.js:10
.class('Queryable') .define({
      ^

TypeError: require(...).class is not a function
    at Object.<anonymous> (C:\Users\steve\projects\mos\node_modules\infusionsoft-javascript-api\lib\Queryable.js:10:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\steve\projects\mos\node_modules\infusionsoft-javascript-api\lib\DataContext.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by SSICWeb** [comment]
When using ContactService with the old library it returns a promise:

Infusionsoft Data Context:  Promise {
  promiseDispatch: [Function (anonymous)],
  valueOf: [Function (anonymous)],
  inspect: [Function (anonymous)]
}

However, when I try to return a result with .done(result => { console.log(result) }) it gives an error:

Error: getaddrinfo ENOTFOUND gkcx3ekkxtjacabqty0rgma2exgb.infusionsoft.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'gkcx3ekkxtjacabqty0rgma2exgb.infusionsoft.com'
}

I know you are not maintaining that library, but I wanted to show that it was partially working with my setup.

**Comment by mkalygin** [comment]
@SSICWeb this is caused by the `typedef` package upgrade in f90c0cf7c6c95087dbaf1a1df2bf2e9d3b107f90. Do `npm install infusionsoft-javascript-api@0.3.1` and it should work.

**Comment by justinhandley** [comment]
The root cause here was the `typedef` 1.1.0 upgrade: that release no longer exposes the `.class()` API used throughout the generated XML-RPC definitions.

The fix is now merged in #12. It removes the broken external `typedef` dependency, provides the small compatibility surface required by the generated definitions, updates Underscore, and adds regression tests covering package loading, generated metadata, `DataContext`, service calls, and queries.

The repository has also been renamed to `keap-xmlrpc`. I’m leaving this issue open only until `keap-xmlrpc@1.0.0` and the `infusionsoft-javascript-api@0.3.2` compatibility alias are published to npm; I’ll post the final install instructions and close it once those releases are live.

**Comment by justinhandley** [comment]
Released and verified:

- [`keap-xmlrpc@1.0.0`](https://www.npmjs.com/package/keap-xmlrpc) contains the fix.
- [`infusionsoft-javascript-api@0.3.2`](https://www.npmjs.com/package/infusionsoft-javascript-api) is a compatibility alias that re-exports `keap-xmlrpc`, so existing imports can update without an immediate code change.
- The release is tagged as [`v1.0.0`](https://github.com/pirateandfox/keap-xmlrpc/releases/tag/v1.0.0).

For new installs:

```sh
npm install keap-xmlrpc
```

Then change `require('infusionsoft-javascript-api')` to `require('keap-xmlrpc')`.

For the smallest immediate upgrade to an existing application:

```sh
npm install infusionsoft-javascript-api@0.3.2
```

That resolves the `require(...).class is not a function` failure caused by the incompatible external `typedef` release. Closing this as fixed.
