### ISSUE TITLE
Error: Unknown XML-RPC tag 'FAULTSTRING' when getting company records

### ISSUE THREAD

**Issue by Kezzsim** [justinhandley/infusionsoft-javascript-api#5]
Greetings

I've been using this to access company records, recently I get this error message when trying to retrieve the company records using this library:
```
srv-3        | XML LIBRARY ERROR
srv-3        | Error: Unknown XML-RPC tag 'FAULTSTRING'
srv-3        |     at Deserializer.onError (/home/node/app/node_modules/xmlrpc/lib/deserializer.js:109:20)
srv-3        |     at Deserializer.onClosetag (/home/node/app/node_modules/xmlrpc/lib/deserializer.js:202:14)
srv-3        |     at SAXStream.emit (events.js:198:13)
srv-3        |     at SAXParser.me._parser.(anonymous function) [as onclosetag] (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:220:15)
srv-3        |     at emit (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:325:33)
srv-3        |     at emitNode (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:330:3)
srv-3        |     at closeTag (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:547:5)
srv-3        |     at SAXParser.write (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:958:29)
srv-3        |     at SAXStream.write (/home/node/app/node_modules/xmlrpc/node_modules/sax/lib/sax.js:202:16)
srv-3        |     at IncomingMessage.ondata (_stream_readable.js:709:20)
srv-3        |     at IncomingMessage.emit (events.js:198:13)
srv-3        |     at IncomingMessage.Readable.read (_stream_readable.js:504:10)
srv-3        |     at flow (_stream_readable.js:973:34)
srv-3        |     at resume_ (_stream_readable.js:954:3)
srv-3        |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Here's an example of the node code we have to do the retrieval**

```
let fields = ['AccountId', 'Address1Type', 'Address2Street1', 'Address2Street2', 'Address2Type', 'Address3Street1',
                    'Address3Street2', 'Address3Type', 'Anniversary', 'AssistantName', 'AssistantPhone', 'BillingInformation', 'Birthday',
                    'City', 'City2', 'City3', 'Company', 'CompanyID', 'ContactNotes', 'ContactType', 'Country', 'Country2', 'Country3', 'CreatedBy',
                    'DateCreated', 'Email', 'EmailAddress2', 'EmailAddress3', 'Fax1', 'Fax1Type', 'Fax2', 'Fax2Type', 'FirstName', 'Groups', 'Id',
                    'JobTitle', 'LastName', 'LastUpdated', 'LastUpdatedBy', 'MiddleName', 'Nickname', 'OwnerID', 'Password', 'Phone1', 'Phone1Ext',
                    'Phone1Type', 'Phone2', 'Phone2Ext', 'Phone2Type', 'Phone3', 'Phone3Ext', 'Phone3Type', 'Phone4', 'Phone4Ext', 'Phone4Type', 'Phone5',
                    'Phone5Ext', 'Phone5Type', 'PostalCode', 'PostalCode2', 'PostalCode3', 'ReferralCode', 'SpouseName', 'State', 'State2', 'State3',
                    'StreetAddress1', 'StreetAddress2', 'Suffix', 'Title', 'Username', 'Validated', 'Website', 'ZipFour1', 'ZipFour2', 'ZipFour3'];
                return ifs.DataService.load('Company', id, fields).then(companySQL => {})
```

Any ideas why this library would suddenly stop working?

**Comment by Kezzsim** [comment]
Actually it's just because my token was being refreshed by another service I was not connected to. It's no issue.

**Comment by justinhandley** [comment]
Glad you sorted it out!
